name: Archive

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - shell: bash
        run: |
          cp -a setup.sh setup-dotfiles.sh
          sed -i "s@REPLACE_ME_TO_BASE64_TAR_GZ@$(tar cz bin Library .gitconfig .gitmessage .zshrc | base64)@" setup-dotfiles.sh

      - name: 'Upload'
        uses: actions/upload-artifact@v2
        with:
          name: setup-dotfiles.sh
          path: setup-dotfiles.sh
          retention-days: 1
